### ISSUE TITLE
Create maps for cross-correlation between Pauling - CRU / Luterbacher - CRU

### ISSUE THREAD

**Issue by imarkonis** [KVHEM/XEROS#26]
Create seasonal maps of cross-correlation of precipitation/temperature for 1900-2000. Each grid cell will present the value of cross-correlation between Pauling - CRU or Luterbacher - CRU. 

The file maps_cor_bias.R should be saved in bias folder.

**Comment by imarkonis** [comment]
There is some bug in temperature, perhaps because cell_id in raster_template correspond to precipitation.

In addition, change figures to be similar with precipitation.

**Comment by veronikacejkova** [comment]
Hi, can you specify the bug for me? Is precipitation data not plotted properly? I ´ve got long / lat switched with precipitation plot and I don´t know why I keep having this problem but I always check my result and I would never send it to you switched so I am bit confused about this problem. 
Are we having the same output at this point?

[precip.pdf](https://github.com/KVHEM/XEROS/files/3617194/precip.pdf)
[temp.pdf](https://github.com/KVHEM/XEROS/files/3617197/temp.pdf)

**Comment by imarkonis** [comment]
Hi, this is strange. I got reversed lat/long (see image). Can you try to run it with the space environment empty? You can do this by changing project options and restarting. 

![options](https://user-images.githubusercontent.com/6950590/65490131-dfae6400-deac-11e9-98de-e310426d3c02.png)

![precip](https://user-images.githubusercontent.com/6950590/65489889-67e03980-deac-11e9-872c-2c7f84d5cc9f.PNG)

**Comment by veronikacejkova** [comment]
Still the same. My latest contribution creates the same output as I send earlier. Is your pauling/luterbacher/CRU dataset right? I remember that I was quite messy at the beginning with long/lat so It could be possible that you save original .rds file with these values switched.

**Comment by imarkonis** [comment]
Found the bug in import luterbacher. I will fix it and rerun everything just to be sure.

![image](https://user-images.githubusercontent.com/6950590/66037917-f8ec8b80-e510-11e9-8b11-36697030f713.png)

In addition, I am changing the whole dir structure to make it more efficient and will notify you when all is done.
