### ISSUE TITLE
Upload pauling.nc to an online repository for reproducibility

### ISSUE THREAD

**Issue by imarkonis** [KVHEM/XEROS#29]
https://zenodo.org/ 

Find data at: 
https://owncloud.cesnet.cz/index.php/s/NiY6dF2JfYTN1Ds

**Comment by MiRoVaGo** [comment]
Navigating through the folders I found ".rds" data and not ".nc" files at:
https://owncloud.cesnet.cz/index.php/s/NiY6dF2JfYTN1Ds?path=%2Fdata%2Finput%2Fgridded%2Fpauling
The Pauling folder doesn't include a subfolder "raw" as the Luterbacher folder does.
Am I looking into the wrong directory or the ".nc" file is actually missing?
Please advise

**Comment by MiRoVaGo** [comment]
To upload the file into "https://zenodo.org/"
Mandatory fields are:
-Publication date (if already published elsewhere)
-Authors
-Description
-Access Right (open, embargoed, restricted, closed)
-License (depending on access selection)
-Grant (if any)

**Comment by imarkonis** [comment]
@MiRoVaGo Can you please check if it is straightforward to dload a file at zenodo using R?

**Comment by MiRoVaGo** [comment]
@imarkonis 
I just tested the following:
`file_url <- "https://zenodo.org/record/2594778/files/data_inventory.rds?download=1"
download.file(file_url,"data_inventory.rds","wget")`
To download the file at "https://zenodo.org/record/2594778#.XdZ-93VKg5k", and download was successful.

**Comment by imarkonis** [comment]
Used for evaluation of https://www.nature.com/articles/s41598-018-27464-4?fbclid=IwAR2Ysvhj1ErZQDmU1E6dlpsHgY0SF9_qwpPE3JgL3KevTRO-gAlyHFob2ik

**Comment by imarkonis** [comment]
Authors for the rest of the dataset: Nasreen, Vargas, Markonis, Maca, Hanel

**Comment by MiRoVaGo** [comment]
Data can be found at https://zenodo.org/record/3552399/files/pauling.nc?download=1
