### ISSUE TITLE
Download pauling.nc to import_pauling.R

### ISSUE THREAD

**Issue by imarkonis** [KVHEM/XEROS#30]
After an upload there should be a download :)

**Comment by MiRoVaGo** [comment]
https://zenodo.org/record/2594778/files/data_inventory.rds?download=1

**Comment by hanel** [comment]
What I downloaded using the link above is for sure not Pauling data, see:

    MET PAR REG VAR   YR SEVERITY        AREA  ID RANK_SEV RANK_AREA
1     8   2 MED   q 1766 2.399187 0.171650718 8_2      201     231.0
2     8   2 CEU   q 1766 1.550382 0.168062201 8_2       91     131.0
3     8   2 MED   q 1767 1.995953 0.149521531 8_2      160     216.0

(its name was data_inventory.rds) - is it ok?

**Comment by MiRoVaGo** [comment]
@hanel I apologize, that was the wrong link. Please try this one instead:
https://zenodo.org/record/3552399/files/pauling.nc?download=1

**Comment by imarkonis** [comment]
The download code should be in file import_pauling.R - User should download the file when running the script
