### ISSUE TITLE
Upload & download various datasets

### ISSUE THREAD

**Issue by imarkonis** [KVHEM/XEROS#32]
Similar to issues 29/30 for 
CRU data in file import_cru_ts4_01.R (name: European hydroclimatology derrived from CRU ts 4.01 dataset) 
PAGES2k in import_pages.R
GHCN in import_ghcn_p.R
OWDA in timescales (publication: https://www.nature.com/articles/s41467-018-04207-7)
grdb in grdb_prep (see https://www.bafg.de/GRDC/EN/01_GRDC/13_dtbse/database_node.html)

**Comment by MiRoVaGo** [comment]
**CRU:** https://zenodo.org/record/3552420/files/cru_pet_mon.nc?download=1
https://zenodo.org/record/3552420/files/cru_pre_mon.nc?download=1
https://zenodo.org/record/3552420/files/cru_tavg_mon.nc?download=1
**PAGES2K:** https://zenodo.org/record/3552420/files/PAGES2k_v2.0.0.RData?download=1
**GHCN:** https://zenodo.org/record/3552420/files/precip_d_source_knmi.txt?download=1
https://zenodo.org/record/3552420/files/precip_m_source_knmi.txt?download=1
**OWDA:** https://zenodo.org/record/3552416/files/owda_1000.rds?download=1
**GRDB:** https://zenodo.org/record/3552420/files/GRDB_long.csv?download=1
https://zenodo.org/record/3552420/files/raw.zip?download=1

**Comment by imarkonis** [comment]
See comment on issue #30
